### ISSUE TITLE
Comments are cut off in reply drawer

### ISSUE THREAD

**Issue by usselman** [zer0dt/hodlocker#43]
Appears that sometimes comments do not clip at the edge of the textbox. Might have something to do with URLs not truncating?

Not clipping:
<img width="1440" alt="Screenshot 2024-02-10 at 2 46 06 PM" src="https://github.com/zer0dt/hodlocker/assets/19578049/1f59f3e9-8908-4bed-837e-9e5bf7d60a1f">
Clipping:
<img width="1440" alt="Screenshot 2024-02-10 at 2 46 13 PM" src="https://github.com/zer0dt/hodlocker/assets/19578049/2eccfbe0-85f5-43a8-a954-f11762040ce4">

**Comment by zer0dt** [comment]
fixed in https://github.com/zer0dt/hodlocker/commit/9ae3d542689f1589de745c8728bad2e273d41090
